---
- name: Reset Kubernetes
  shell: echo $(kubeadm reset && echo 'true') 

- name: Remove docker images
  shell: echo $(docker rmi --force $(docker images --all -q) && echo 'true')
  become: true

- name: Update apt packages
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: Purge apt packages
  apt:
    name: 
        - kubelet
        - kubeadm
        - kubectl
        - docker-ce
    state: absent
    purge: yes
    autoremove: yes
    force: yes

- name: Remove /var/log/pods
  file:
    path: /var/log/pods
    state: absent

- name: Remove /etc/kubernetes
  file:
    path: /etc/kubernetes
    state: absent

- name: Remove /var/lib/etcd
  file:
    path: /var/lib/etcd
    state: absent

- name: Remove ~/.kube
  file:
    path: ~/.kube
    state: absent

- name: Reboot Raspberry Pis
  shell: sleep 2 && reboot "Ansible Reboot"
  async: 1
  poll: 0
  ignore_errors: True

- name: Wait for reboot
  wait_for_connection:
    delay: 30
    timeout: 120
