---
- name: Reseting worker nodes
  become_user: root
  shell: kubeadm reset -f

- name: Joining a master node at {{ hostvars['node00prod'].ansible_host }}:6443
  become_user: root
  shell: kubeadm join {{ hostvars['node00prod'].ansible_host }}:6443 --token {{ token }} --discovery-token-unsafe-skip-ca-verification

- name: Rebooting worker nodes
  become_user: root
  shell: sleep 2 && reboot "Rebooting worker nodes"
  async: 1
  poll: 0
  ignore_errors: True
  when: cmdline or timezone or hostname is changed

- name: Waiting for reboot
  wait_for_connection:
    delay: 15
    timeout: 120