---

- name: Reset Kubernetes
  shell: kubeadm reset -f
  register: kubeadm_reset

- name: Worker nodes joining Kubernetes master {{ hostvars[master_node].ansible_host }}
  shell: kubeadm join {{ hostvars[master_node].ansible_host }}:6443 --token {{ token }} --discovery-token-ca-cert-hash {{ ca_cert_hash }}
  become: yes
  when: kubeadm_reset is succeeded
  register: kubeadm_join

- name: Poke kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: kubeadm_join
  register: kubelet_poke
