---
# tasks file for master
- name: Reset Kubernetes masters
  become_user: root
  shell: kubeadm reset -f
  register: kubeadm_reset
- debug: msg={{ kubeadm_reset.stdout }}

- name: "Initialize Kubernetes masters"
  become_user: root
  shell: kubeadm init  --token={{ token }} --apiserver-advertise-address={{ hostvars['node01'].ansible_host }} --kubernetes-version={{ kubernetes_version }} --node-name={{ groups['master_nodes'][0] }} --pod-network-cidr={{ pod_network_cidr }}
  register: kubeadm_init
  when: kubeadm_reset is succeeded
  become: yes
- debug: msg={{ kubeadm_init.stdout }}

- name: Create Kubernetes config file
  become_user: root
  shell: kubeadm config images pull
  register: kube_config
- debug: msg={{ kube_config.stdout }}

- name: Create Kubernetes /root/.kube directory
  become_user: root
  file:
    path: /root/.kube/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy /etc/kubernetes/admin.conf to /root/.kube/config
  become_user: root
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    owner: root
    group: root
    mode: 0755
    remote_src: yes
    backup: yes
  become: yes
  when: kubeadm_init

- name: Create Kubernetes /home/pi/.kube folder
  become_user: root
  file:
    path: /home/pi/.kube
    state: directory
    owner: pi
    group: pi
    mode: u=rw,g=rw,o=rw
  when: kubeadm_init
  register: kubedir

- name: Copy /etc/kubernetes/admin.conf to /home/pi/.kube/config
  become_user: root
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/pi/.kube/config
    remote_src: yes
    backup: yes
  when: kubedir
  register: kubefile

- name: chown for /home/pi/.kube/config file
  become_user: root
  file:
    path: /home/pi/.kube/config
    owner: pi
    group: pi
    mode: u=rw,g=rw,o=rw
  become: yes

# kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/{{ flannel_version }}/Documentation/kube-flannel.yml
- name: Install Flannel (Networking)
  become_user: root
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/{{ flannel_version }}/Documentation/kube-flannel.yml
  register: flannel_installed
- debug: msg={{ flannel_installed.stdout }}

- name: Reboot the master
  shell: sleep 2 && reboot "Ansible Reboot"
  async: 1
  poll: 0
  ignore_errors: True
  when: cmdline or timezone or hostname is changed

- name: Wait for reboot
  wait_for_connection:
    delay: 15
    timeout: 120